function trial_table = events_to_trial_table(events, distances_to_m2s_eyes, m2_dist_to_m1s_eyes, m2_dist_is_valid)

%{
m1_hemifield_origin_delta_pos
%}

sessions = events.labels{:, 'session'};
fixation_start_ts = events.events(:, events.event_key('start_time'));
fixation_stop_ts = events.events(:, events.event_key('stop_time'));
m1_fix_durations = (fixation_stop_ts - fixation_start_ts) * 1e3;    %   to ms

trial_table = table( ...
    sessions ...
    , fixation_start_ts ...
    , fixation_stop_ts ...
    , m1_fix_durations ...
    , distances_to_m2s_eyes ...
    , m2_dist_to_m1s_eyes ...
    , m2_dist_is_valid ...
);

end